quarkus.grpc.clients.customer-service.host=localhost
quarkus.grpc.clients.customer-service.port=9090
quarkus.grpc.clients.product-service.host=localhost
quarkus.grpc.clients.product-service.port=9090

quarkus.openapi-generator.codegen.spec.openapi_yaml.mutiny=true

scheduler.socket-inactive.max-period=10m
scheduler.socket-inspection.interval=1m